### PR TITLE
Enable gcp/openstack as cloud provider

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by gbraad** [comment]
I think the next step would be to actually separate these implementations in a more programmatic way; instead of `_aws` and `_gcp`.

**Comment by lmilbaum** [comment]
It would be easier to validate if IaC solution like terraform+ansible is adopted before moving on with supporting additional cloud vendors.  Does it make sense?

**Comment by gbraad** [comment]
> terraform+ansible

Pulumi ?

**Comment by lmilbaum** [comment]
> > terraform+ansible
> 
> Pulumi ?

Yup. This is also a good option. @ginger would you like to take a look at it?

**Comment by praveenkumar** [comment]
Closing it because this is now implemented on pulumi side.

**Pull request closed without merging**
